version: '3.0'

services:

  nginx:
    container_name: 'nginx'
    image: 'nginx:1.13'
    restart: 'always'
    links: 
      - 'mariadb'
    ports:
      - 80:80
      - 443:443
    volumes:
      - './bot:/var/www/html'
      - './data/nginx:/etc/nginx/conf.d'
      - './data/certbot/conf:/etc/letsencrypt'
      - './data/certbot/www:/var/www/certbot'

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
      
  php:
    container_name: 'php'
    build: './.docker'
    links:
      - 'mariadb'
    restart: 'always'
    volumes:
      - './bot:/var/www/html'
    depends_on:
      - 'nginx'
  
  mariadb:
    container_name: 'mariadb'
    image: 'mariadb'
    restart: 'always'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_DATABASE: 'db_name'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'db_password'